### ISSUE TITLE
Image filename not year + month + day etc.

### ISSUE THREAD

**Issue by Spiritdude** [an-rahulpandey/cordova-plugin-camerapicturebackground#10]
Thanks for the plugin.

A small issue with the image filename, the naming is bizarre, `new SimpleDateFormat("yyyymmddhhmmss");` as defined in `CameraSurfacePreview.java` line 116, how does the first `mm` (supposed month) and the `mm` (supposed minutes) near the end differentiate?

My resulting filename as example looks like this:
`Image-20173115073157.jpg`

- `2017` (year correct)
- `31` (month, incorrect, more like minutes)
- `15` (day, correct)
- `07` (hours, correct)
- `31` (minutes, correct)
- `57` (seconds, correct)

Solution: According http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html for month the uppercase M is needed: `new SimpleDateFormat("yyyyMMddhhmmss");`

I just changed it in my local copy and now it's correct with the suggested solution.

**Comment by an-rahulpandey** [comment]
Thanks for noticing it, can you send a PR?

**Comment by an-rahulpandey** [comment]
#11
