### ISSUE TITLE
0 device compatibles

### ISSUE THREAD

**Issue by crmolinaz** [an-rahulpandey/cordova-plugin-camerapicturebackground#3]
hey!

Thank you for sharing.  i have to change some lines into the plugin.xml to do more compatible my app.

![image](https://cloud.githubusercontent.com/assets/14848371/11320722/7a3ca560-90a3-11e5-8f1c-7d212b00503d.png)

If i don't change anything, i cannot install the app in other devices (from playstore)

**Comment by an-rahulpandey** [comment]
Thanks for the information. This is the required feature without it plugin cannot work -

```
<uses-feature android:name="android.hardware.camera" />
```

**Comment by crmolinaz** [comment]
yes, i knew it. 

But on my device, it does. If you change and put required="false", and you keep the same configuration, will work with others devices.
